--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Julicraft44/DayNightVoting
build-by-default: true
branches:
- main
projects:
  DayNightVoting:
    path: ""
    lint:
        phpstan: false
    icon:
        icon.jpg
...
